image: docker:20.10

services:
  - docker:dind

stages:
  - build
  - test
  - release
  - preprod
  - integration
  - prod

semgrep:
  image: returntocorp/semgrep

  rules:
  - if: $CI_MERGE_REQUEST_IID

  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

  variables:

    SEMGREP_APP_TOKEN: $SEMGREP_APP_TOKEN

    # Upload findings to GitLab SAST Dashboard:
    SEMGREP_GITLAB_JSON: "1"

  script: semgrep ci --supply-chain --output semgrep-sca-output.json --json
  artifacts:
    paths: [semgrep-sca-output.json]
    when: always
  allow_failure: true
